### ISSUE TITLE
`make verify` workflow doesn't validate the `examples/**` components. 

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes-sigs/e2e-framework#280]
The defaults used by the `golangci-lint` for `--skip-dirs-use-default` includes `- (^|/)examples($|/)` and `- (^|/)third_party($|/)`

As a side effect of this, none of the code that we have in `examples/**` is getting linted. We should probably fix this. Here is what needs to be done to enable this. 

1. Modify the existing `.golangci.yml` to include the following
```yaml
run:
  concurrency: 6
  deadline: 5m
  skip-dirs-use-default: false
  skip-dirs:
    - (^|/)vendor($|/)
    - (^|/)testdata($|/)
    - (^|/)Godeps($|/)
    - (^|/)builtin($|/)
```
2. Once we are done with that, a series of linter checks will fail on the examples
3. Disable the following linters on the examples dir 
```yaml
    - path: examples/*
      linters:
        - dupl
        - staticcheck
        - gocritic
        - stylecheck
        - misspell
```

4. Enable `revive` to detect diplicate imports across the components
```yaml
  revive:
    confidence: 0.01
    rules:
      - name: duplicated-imports
        severity: error
        disabled: false
```

Opening this as a catch all fix based on what was see in https://github.com/kubernetes-sigs/e2e-framework/pull/279
