### ISSUE TITLE
Failed to create cluster with kind podman

### ISSUE THREAD

**Issue by heylongdacoder** [kubernetes-sigs/e2e-framework#347]
### What happened?

Error returned in `CreateCluster` function.

Error:
```
F1104 16:46:26.675423   12330 env.go:375] Setup failure: error loading config file "/var/folders/gk/jhz_72bs7830pb6pq1ywhcm00000gp/T/kind-cluser-test-58ebc2614499a2d22e72edbf54f-kubecfg1049500896": yaml: line 2: mapping values are not allowed in this context
```

Content of `/var/folders/gk/jhz_72bs7830pb6pq1ywhcm00000gp/T/kind-cluser-test-58ebc2614499a2d22e72edbf54f-kubecfg1049500896`:

```
enabling experimental podman provider
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1URXdOREE0TkRZeE0xb1hEVE16TVRFd01UQTRORFl4TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3ZXCnAzdURIUVIvKzlTUGlpeVpQTU4wSHVTSUg5QUc1eEUvZGxnbmpmSkJweXVKa0pYanE5bGVSVTF4Qmw0QmJEbWwKT2NaZUVTZ3N4blEyaU1KNEl4QSt0MWNaNk01bmVsQlRsdU8zM2krYmNaQks3UEh6TVJBL0p1V0lWTnV4S3FuRgpJWmpqY0dWeFBrT3MwS2JVcTJIbWpRUWpuZE41eWkzZkJsazRpWGNmdWU0Y2psS25uQmYwNjBYL0tZNG9oek5ICi94REdCekFvSzNiU3pzZWpPa0VRZTZIZVM5Z1Z1a3Y0UXVjTFdzY2h1dkR2UXYzclNrbGZZQmVNN3ZwZE5aRisKaEhGUzhuZVIwM2dmNy9rNzhMYysxQm1kVndkc2paQ3JUMEY4bzhwY01WempQSUFyQkhIQU1XS3BqVCtnaTlpago5YlRkK21xS3Avd3FLc01sRWxjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZObXkwMk8xVWRaeEdkVFVPQWhFMUwyMkFOSENNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR3dXTDU5ZGtJZEkvYUFEM25iTwovL05aZUJGUHVvNS9OTjNsWjZ5SGp6U2hRT2RnNEM3aDI4Z29XUHMxRk50Z3ZNN1Q2U0l2TUd1b05wdUY3RmRUClJ3R1NEU2N1OFVja0lXdUJ3cjI1VHhzaVdqVGs5a2l0QVp1dzgyN21pd2Z0OGdiMGFJRU94S3ZrTkx4Y3ZqRGUKTHYvRFNVTXVWazdRSnNSV2hYdGZObUFCSXZBcEt6YXd0NDVicllPNFpSVGtBSVRCNGVjNGFoZ3BnZ1RpYzIvKwpJNmVESlRBVGpFbDNtMHcwS1V4STFMS0xwY1BwYk1pSytyNE5uT2tVN055Mmk4NjdneVBqT1llUEtXVExXR2NNCmtTS2ZWbmc5L3p0QzFQbGpHQktuNTVrbDlXMUtiRVAxaEZyR3ArMlUrTGRXMEdwWW95bEJTNmZGaEdjK1A4VVEKd0xZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:49978
  name: kind-test-58ebc2614499a2d22e72edbf54f
contexts:
- context:
    cluster: kind-test-58ebc2614499a2d22e72edbf54f
    user: kind-test-58ebc2614499a2d22e72edbf54f
  name: kind-test-58ebc2614499a2d22e72edbf54f
current-context: kind-test-58ebc2614499a2d22e72edbf54f
kind: Config
preferences: {}
users:
- name: kind-test-58ebc2614499a2d22e72edbf54f
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJUDdZMW92eXJpdUl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1EUXdPRFEyTVROYUZ3MHlOREV4TURNd09EUTJNVFJhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBRMzVXT3BmaEJObXpoV20KOUNFSERKOHdrL3QyNlZHbitXZmRZRDRETmZIZXN5VEtkMDMrSDhyT2FRUUlLVXdpYitmQ1l2QmhGUEJwaE1VeAorNjVlY2dDdTZFVG4wZndDanhJS2hCSnZiYlBDTUtENlp1OXhOdy9BZEljaG1zbGI4VVh6aG0vY1Nkc3A1OWppCk40cUZkNzA0VUxzMEV3UVMvdnNlQk4xZ2tVU2NGSm5IMUt1R284eGRieFp3Nnc2N21GMVlnSndoOE5ka25vOTEKUnltd0h1eThYakt2NnFJRHYxWlh2Z1drSkF4TElQT3kzcG5jV29uTldBV0ttUlVrckNWb1U4UVkxRWszZjdaTgpVaWxjSEcyTzFuWUVMdHZjRFlXQUMyTkVPc0FGVkVybURoT2xXVXR6akdNcTFEdzBUbXFMNGptbEQyWEw2UmpkCjRpdFRUUUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JUWnN0Tmp0VkhXY1JuVTFEZ0lSTlM5dGdEUgp3akFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZE9BL0RmTzNyczYxRTdWWWY1NVJRR3VQemRXaVBIb0tEOFFjCnc1MllNVVQ1T1ZnNXptTmV4cHNoZm5Oc2loSjNhUnN6MkFrMVVSTnpoemJjRkhGMXUzT05VVm8vcUFHTVF2MDYKcEVOek1QWWUxVG5IblZFWG1BUkRSMTlTektQeUpOekRMc3o4cW5Yd3VBU1ZreFJIUDY0dU0xVWRMbVRKc1B0dQo0ejRYNWNpZnFJR0ROMlpvT1lJVFNHbzRYU2FtWjFXMUNuQzl1R3BmSlBJUUs2TTJjRFBtR1FHSXlDcUdYZkNICjBtWkk2R09hTXNteUFTandxZU9NMGJ3dUhrcXQ1Q09Ia2xPeHNrWGVLcjhWM0laODNGdFJkNGErNGtKdVJMOEIKczE5MnZYRjFIQUd2UUhic1U5Ky9VcU5jSDRrNUZ1VlNJdjI5ZldMV28rcFdyeHdjSlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcFEzNVdPcGZoQk5temhXbTlDRUhESjh3ay90MjZWR24rV2ZkWUQ0RE5mSGVzeVRLCmQwMytIOHJPYVFRSUtVd2liK2ZDWXZCaEZQQnBoTVV4KzY1ZWNnQ3U2RVRuMGZ3Q2p4SUtoQkp2YmJQQ01LRDYKWnU5eE53L0FkSWNobXNsYjhVWHpobS9jU2RzcDU5amlONHFGZDcwNFVMczBFd1FTL3ZzZUJOMWdrVVNjRkpuSAoxS3VHbzh4ZGJ4Wnc2dzY3bUYxWWdKd2g4TmRrbm85MVJ5bXdIdXk4WGpLdjZxSUR2MVpYdmdXa0pBeExJUE95CjNwbmNXb25OV0FXS21SVWtyQ1ZvVThRWTFFazNmN1pOVWlsY0hHMk8xbllFTHR2Y0RZV0FDMk5FT3NBRlZFcm0KRGhPbFdVdHpqR01xMUR3MFRtcUw0am1sRDJYTDZSamQ0aXRUVFFJREFRQUJBb0lCQUdWVG05VGJKVUlteXdFUApSOHd0am05UU52bFI4ZUV3a09kS3ZSdTlWaWxDMEEyNE0xZGttUEtaaFhmdzByWFBtSUNNamNoQmU4Zm9BMDlQCjQreDNVbUc0UzZncHpRc2JJOU1ESjFPSEljTCtET1BmbjNtYjJ5d0xUb0g3QjBWSUFscXZMOTVEUThCUGZIMXAKcHc2anltWUUwdEswNmpZV1ZUY1ZvSXNxQUlPTTEzNXRIemlUMHpHWUYrNW9weG1MQkpMbGRWcSszVzBzbmhNbwpZTnVKcnpNYVIyWGxGcWIwZEZTdDd2UFFURC9MTmR3RzY2cXJhRkdIa2QyZ3Y3bjhSb1BBa3Y1TkV0NWFHWGRnCjk4Y2ticW5ibVhCUm9RZXl1OEQwT3lMdTlhR3dXYUJ3OEJGMVNrSCtmbFNXVlpIK3VCaTlYT1g2MnBiTHVmUUwKZTBvOTFpRUNnWUVBMTNOK0E1V24vbFI5Q0ZzNW05TCs1djR5eVJFeGFsRnpyaEk0SlVEMFBzV2NQYnVNVjBmRQpubjhZYms4RGxsVGZKQk5ScWsyWUZCSE5mYUVtaTlGY1YyN3dBV1Nla0Zmb2ZYMk5Va3Ryb3pSSC83N0x5R0gxCitlU096QUN2ZHFkVFBsZlc2T2FoeGo4NTF0Tm1rUVNyWjNRS2RnOVNGWkRzbFJOMjBpNHU4Z2tDZ1lFQXhCNWIKNDF6aGtZMXZqcWl4d0lpNnhzQXFYaWpMRWZOYXdrT0lrV2RwY1QzNFNEZnFNTlJTd0c1VHNDczNPT1JqTWZiVQpYMktMV1Y5SHVpYjdhbzBIdDlDZVFJM0JUWmdiazBzVk9xRXBiM0JDenJkSS85V0FqcUxBR0pNODFPVSsreklEClAwVFIrUVFwckx6VFlYY0VaU1AvZVFVVDdwakJ1L0xXQ3ArRm1DVUNnWUFCMHhXUEhEWlcvZ290QnZDKzlCTjYKaTA2TXkxdDZ4Z1BQeHBHNUp3cXFlV3Z3VGVWTFcrMDdWbUl6bFBHMzFUSXFrUXRSQU9VM3prcktOSklwL3ZUawpQS2xGcWI5NkEzU1JrMzJkNDh1ZWp6UEk0Nm5BSWF3K21JUHBFRnhzQ2RDM3AzREhlaVNHbEVSK0lENHZIallCClkwY3Zac1BRTVBELzlqRThhRzIzV1FLQmdRREJ5QTJiVm9jN3ZyamdDU2U1eW1CalNqV1MzRlBxNUw1ay9UM1EKRHBKTlpxSVJHYzY1ZU5KYmVhZ1BobVFHUHdVVXRZT2F6RkJNZXF6dzd0dTFxS3hib0RMK0xoTTJqSG1TekxtcApPTjBzVTR4dm5RTHdaeEdqM29SWXhBTnppU0QySzdDeHIxcVo1dGNXNjIwaC9PdkcxQTcya1dIa2UrUFJ4bHhnCkdzZHlVUUtCZ0YxL3FHSFhqcGpOZm1TdmRZTmNJMVY3VXVyVWNBbmxGOUZ4b0owallwWlFLZjhXUjF3NTg5YkYKakdqV0JWN1lQYW9wOHg4TXhqVHNGKzRiaXppOXJ3bHM4SmVrVGRHRHh5WU81Mk5jdktTZ0tMVmJsbVV0TldYTQpFbXY3MUM3M29hc29IRVp2aUVQSk11cXlBS2FUc2dvR3BBOWtUWHpNVXlQTkxES1lZN01nCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```

I believe there is a bug in this line(https://github.com/kubernetes-sigs/e2e-framework/blob/main/support/kind/kind.go#L119) where `p.Out()` is actually outputting both stdout and stderr(https://github.com/vladimirvivien/gexe/blob/main/exec/proc.go#L206), causing the kubeconfig content to be incorrect.

### What did you expect to happen?

Able to create a kind podman cluster.

### How can we reproduce it (as minimally and precisely as possible)?

Code to reproduce:

```
package e2e

import (
	"os"
	"testing"

	"sigs.k8s.io/e2e-framework/pkg/env"
	"sigs.k8s.io/e2e-framework/pkg/envconf"
	"sigs.k8s.io/e2e-framework/pkg/envfuncs"
	"sigs.k8s.io/e2e-framework/support/kind"
)

var testenv env.Environment

func TestMain(m *testing.M) {
	testenv, _ = env.NewFromFlags()
	kindClusterName := envconf.RandomName("test", 32)

	testenv.Setup(
		envfuncs.CreateCluster(kind.NewProvider(), kindClusterName),
	)

	os.Exit(testenv.Run(m))
}
```

### Anything elese we need to know?

Version:

kind: 0.20.0
podman: 4.6.2

### E2E Provider Used

kind

### `e2e-framework` Version

v0.3.0

### OS version

MacOS M2 chip
